Repository geopandas/geopandas, pull requests merged in 2020-04, with the labels that each got.

#1348 DOC: remove six as a depenency
  doc/source/install.rst
Labels: documentation

#1339 ENH: move CRS to GeometryArray level
  doc/source/projections.rst
  geopandas/array.py
  geopandas/base.py
  geopandas/geodataframe.py
  geopandas/geoseries.py
  geopandas/testing.py
  geopandas/tests/test_crs.py
  geopandas/tests/test_geodataframe.py
  geopandas/tests/test_testing.py
  geopandas/tools/overlay.py
Labels: enhancement

#1375 BUG: CRS not propagated to GeometryArray based on scalar
  geopandas/geodataframe.py
  geopandas/tests/test_crs.py
Labels: bug

#1255 BUG: Set operators are inconsistently handled
  geopandas/geodataframe.py
  geopandas/tests/test_geom_methods.py
Labels: bug

#1215 DOC: add example of appending GeoSeries
  doc/source/mergingdata.rst
Labels: documentation

#1329 ENH: Read filelike objects
  doc/source/io.rst
  geopandas/io/file.py
  geopandas/io/tests/test_file.py
Labels: enhancement

#802 ENH: allow explicit CRS setting in to_file
  geopandas/io/file.py
  geopandas/tests/test_geodataframe.py
Labels: crs

#1343 ENH: add PyGEOS spatial index
  benchmarks/sindex.py
  geopandas/_compat.py
  geopandas/base.py
  geopandas/sindex.py
  geopandas/tests/test_overlay.py
  geopandas/tests/test_sindex.py
  geopandas/tools/tests/test_sjoin.py
Labels: enhancement
