Repository geopandas/geopandas, pull requests merged in 2020-05, with the labels that each got.

#1426 CI: add a build without optional dependencies
  .travis.yml
  ci/travis/38-no-optional-deps.yaml
  geopandas/tests/test_overlay.py
  geopandas/tests/test_sindex.py
  geopandas/tools/tests/test_clip.py
Labels: Testing

#1123 ENH: Read from postgis in chunks
  geopandas/geodataframe.py
  geopandas/io/sql.py
  geopandas/io/tests/test_sql.py
Labels: enhancement

#1445 BUG: explode() fails if 'level_1' is in columns
  geopandas/geodataframe.py
  geopandas/tests/test_geom_methods.py
Labels: bug
