Repository geopandas/geopandas, pull requests merged in 2021-09, with the labels that each got.

#2125 DOC: fix RTD builds
  doc/environment.yml
Labels: documentation

#1955 BUG: active geometry information lost after apply
  geopandas/geodataframe.py
  geopandas/tests/test_pandas_methods.py
Labels: bug

#2019 BUG: preserve color map according to bins
  geopandas/plotting.py
  geopandas/tests/test_plotting.py
Labels: bug, plotting
