Repository geopandas/geopandas, pull requests merged in 2021-01, with the labels that each got.

#1767 TST: skip test_argreduce_series
  geopandas/tests/test_extension_array.py
Labels: Testing

#1790 TST: skip pandas EA test
  geopandas/tests/test_extension_array.py
Labels: Testing

#1693 ENH: integrate pygeos.get_parts for faster explode()
  benchmarks/geom_methods.py
  geopandas/_compat.py
  geopandas/geoseries.py
Labels: enhancement

#1750 DOC: documentation improvements
  doc/source/docs/reference/geodataframe.rst
  doc/source/docs/reference/geoseries.rst
  geopandas/array.py
  geopandas/base.py
  geopandas/datasets/__init__.py
  geopandas/geodataframe.py
  geopandas/geoseries.py
  geopandas/plotting.py
  geopandas/tools/clip.py
  geopandas/tools/overlay.py
  geopandas/tools/sjoin.py
Labels: documentation
