Repository geopandas/geopandas, pull requests merged in 2023-06, with the labels that each got.

#2902 ENH: add offset_curve as GeoSeries method
  CHANGELOG.md
  doc/source/docs/reference/geoseries.rst
  doc/source/docs/user_guide/geometric_manipulations.rst
  geopandas/_vectorized.py
  geopandas/array.py
  geopandas/base.py
  geopandas/tests/test_geom_methods.py
Labels: shapely parity

#2903 ENH: add concave_hull as GeoSeries method
  CHANGELOG.md
  doc/source/docs/reference/geoseries.rst
  doc/source/docs/user_guide/geometric_manipulations.rst
  geopandas/_vectorized.py
  geopandas/array.py
  geopandas/base.py
  geopandas/tests/test_geom_methods.py
Labels: shapely parity

#2909 ENH: add hausdorff distance method
  CHANGELOG.md
  doc/source/docs/reference/geoseries.rst
  geopandas/_vectorized.py
  geopandas/array.py
  geopandas/base.py
  geopandas/tests/test_geom_methods.py
Labels: shapely parity

#2915 ENH: add extract_unique_points as a GeoSeries property
  CHANGELOG.md
  doc/source/docs/reference/geoseries.rst
  doc/source/docs/user_guide/geometric_manipulations.rst
  geopandas/_vectorized.py
  geopandas/array.py
  geopandas/base.py
  geopandas/tests/test_geom_methods.py
Labels: shapely parity

#2923 BUG: fix a color assignment in ``explore`` when using ``UserDefined`` bins
  CHANGELOG.md
  ci/envs/310-dev.yaml
  ci/envs/310-latest-conda-forge.yaml
  ci/envs/311-latest-conda-forge.yaml
  ci/envs/38-latest-conda-forge.yaml
  ci/envs/38-latest-defaults.yaml
  ci/envs/38-minimal.yaml
  ci/envs/38-pd12-defaults.yaml
  ci/envs/39-latest-conda-forge.yaml
  ci/envs/39-pd13-conda-forge.yaml
  geopandas/explore.py
  geopandas/tests/test_explore.py
Labels: bug

#2910 ENH: add segmentize as a GeoSeries method
  CHANGELOG.md
  doc/source/docs/reference/geoseries.rst
  doc/source/docs/user_guide/geometric_manipulations.rst
  geopandas/_vectorized.py
  geopandas/array.py
  geopandas/base.py
  geopandas/tests/test_geom_methods.py
Labels: shapely parity

#2027 Added type hints - geoseries.py
  doc/source/conf.py
  geopandas/geoseries.py
Labels: type-hints
