Repository geopandas/geopandas, pull requests merged in 2024-03, with the labels that each got.

#3175 ENH: `set_precision` and `get_precision` methods
  CHANGELOG.md
  doc/source/docs/reference/geoseries.rst
  geopandas/array.py
  geopandas/base.py
  geopandas/tests/test_geom_methods.py
Labels: shapely parity

#3167 BUG: support psycopg3 in .to_postgis()
  CHANGELOG.md
  ci/envs/311-latest-conda-forge.yaml
  doc/source/getting_started/install.rst
  environment-dev.yml
  geopandas/_compat.py
  geopandas/geodataframe.py
  geopandas/io/sql.py
  geopandas/io/tests/test_sql.py
  geopandas/tests/test_api.py
  geopandas/tests/test_show_versions.py
  geopandas/tools/_show_versions.py
  pyproject.toml
  requirements-dev.txt
Labels: postgis

#3221 DOC: remove dysfunctional geoplot example
  doc/source/gallery/plotting_with_geoplot.ipynb
Labels: documentation

#3214 ENH: add line_merge method
  CHANGELOG.md
  doc/source/docs/reference/geoseries.rst
  geopandas/array.py
  geopandas/base.py
  geopandas/tests/test_geom_methods.py
Labels: enhancement, shapely parity
